### ISSUE TITLE
install

### ISSUE THREAD

**Issue by PigUnderRoof** [tanaylab/tglkmeans#1]
Which version of R is compatable? I tried 3.4, 3.5 and 3.6, none of  them works.

**Comment by aviezerl** [comment]
Which command did you run? What was the output? 

The following command should work for all the above R versions :

```r
install.packages('tglkmeans', repos=c(getOption('repos'), 'https://tanaylab.github.io/repo'))
```

or 

```r
remotes::install_github("tanaylab/tglkmeans")
```

**Comment by PigUnderRoof** [comment]
Thanks for ur reply, @aviezerl. I have tried both, the warning message of **install.packages** is _package ‘tglkmeans’ is not available (for R version 3.6.1)._

While for **install_github**, it is _ERROR: dependencies ‘doMC’, ‘ggridges’, ‘pheatmap’, ‘tgstat’ are not available for package ‘tglkmeans’ removing ‘/home/user/miniconda3/envs/test/lib/R/library/tglkmeans’ Error: Failed to install 'tglkmeans' from GitHub: (converted from warning) installation of package ‘/tmp/RtmpWgZLfp/file17a991d279952/tglkmeans_0.3.1.9000.tar.gz’ had non-zero exit status_

I think **install_github** might work if I install the requiring dependencies first.  I also tryied **devtools::install_bitbucket** for tgstat and tglkmeans later yesterday which I found in **clustering3.r**, they seem to work. Are they proper way to install?

**Comment by aviezerl** [comment]
I just initialized an AWS instance with R 3.6.1 and the command worked. Are you sure you used the 'repos' argument? 

If that doesn't work, you can use the *install_github* strategy, after installing tgstat from github:

```r
remotes::install_github("tanaylab/tgstat")
```

The bitbucket versions are fine for now, but we will update the packages only in github, so it is better to use that version.

**Comment by PigUnderRoof** [comment]
Just tested, it works. Perfect solution, thanks! 👍

**Comment by tanmayroy1979** [comment]
This package is for Unix system Only. I am running R from Windows. Do you have any source for Windows?

**Comment by PigUnderRoof** [comment]
You might want to try WSL, very convinient. @tanmayroy1979

**Comment by tanmayroy1979** [comment]
I am also having WSL .. but that doesn't have GUI to support R. i am doing command line work from WSL but R analysis from Windows as host, so asked.
I can install R CMD in WSL but that will also wont have any graphis.

**Comment by aviezerl** [comment]
Hi @tanmayroy1979, 

Unfortunately, we do not support windows currently. The package relies on `tgstat` which would not be trivial to convert to windows due to the parallelism mechanism. If that would change we would let you know. 

Aviezer

**Comment by PigUnderRoof** [comment]
Would you like to  use R with jupyter notebook, in WSL? Linux + GUI @tanmayroy1979

**Comment by kamalmdmostafa** [comment]
I am having a similar issue with my Linux system. 
![tglkmeans](https://user-images.githubusercontent.com/2913622/167557293-9973bce6-b9e3-48b1-b26d-efbcbe972ad1.jpg)
