### ISSUE TITLE
non-zero exit status in Linux

### ISSUE THREAD

**Issue by kamalmdmostafa** [tanaylab/tglkmeans#4]
Can you help me solve this issue in Linux? 
![tglkmeans](https://user-images.githubusercontent.com/2913622/167557420-d2a15d1e-9226-4f4e-987a-9610995edab2.jpg)

**Comment by aviezerl** [comment]
Could you try installing from the [fix@number-of-cores-on-load](https://github.com/tanaylab/tglkmeans/tree/fix%40number-of-cores-on-load) branch? If it would work I would merge it and push to cran: 

```r
remotes::install_github("tanaylab/tglkmeans", branch = "fix@number-of-cores-on-load")
```

**Comment by Cuneyt-C** [comment]
What worked for me was to use **ref** instead **branch**:

remotes::install_github("tanaylab/tglkmeans", ref = "fix@number-of-cores-on-load")

**Comment by aviezerl** [comment]
You are right! The correct API is indeed 'ref' instead of 'branch'. Anyway - the fix is on its way to CRAN.

**Comment by aviezerl** [comment]
This is now fixed in the CRAN version
